repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: flake8
    - id: mixed-line-ending
      args:
      - --fix=no
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.4.3'
    hooks:
    -   id: autopep8
